### ISSUE TITLE
Questions about comparation

### ISSUE THREAD

**Issue by minhlenhat21** [haleqiu/AirIMU#5]
Thank for a great paper

I have a question. I saw that you compared this method with the RoNIN paper in the learning-based inertial odometry task. I see that you trained your method with the KITTI dataset ("We train the AirIMU on the KITTI Odometry datasets") and compared the results with the RoNIN model. However, I don't know if the RoNIN model you used was trained on this dataset or not.

And one more question, have you compared this method with Ronin in the Ronin dataset?

**Comment by haleqiu** [comment]
The RoNIN is also trained on the same training set. We would highlight that in the paper. Thank you for the suggestions.
If there is any other unclear experiment setting, please let me know.

We haven't compared Ronin in the Ronin dataset. 
It may be worth a try, but since the ground truth for RONIN is a VIO. I am not sure if the quality is good enough. Also, the extrinsic between the ground truth and the IMU may be tricky for our model.

**Comment by minhlenhat21** [comment]
Thanks for the quick reply, really appreciate that. 

How can i get the TUM VI  pretrained model

**Comment by haleqiu** [comment]
@minhlenhat21 Just find your questions on the `TUM VI pre-trained model.` Maybe you edit the response. 
We will upload the pre-trained model soon. Right before that we organizing the subtmrs dataset.
