### ISSUE TITLE
motivation for the padding method

### ISSUE THREAD

**Issue by ShenghaoZhou** [haleqiu/AirIMU#9]
Thanks for your great work! I have a question on the padding method used to load the data.
I notice a special collate function named `padding9` is used to load datasets, for both EuRoC and TUM-VI (but not for KITTI). Essentially, it will pad 9 synthetic readings before actual IMU readings. I wonder what the motivation behind this padding scheme is. 
I can see it will make some windows have the desired seq_len, but at the same time, it will make other windows have longer than seq_len length, and some windows still have less than desired seq_len length after padding. I would appreciate it if you could shed light on this.

**Comment by haleqiu** [comment]
Hi @ShenghaoZhou , I noticed that the GRU structure may behave weirdly due to the initial hidden status. This may not have a significant difference for the integration (since the dt is very small), but I found it confusing for my uncertainty estimation. So, I add padding with some simulated data with gravity. 

Feel free to play around and see if you can find anything.

**Comment by ShenghaoZhou** [comment]
Thanks for your feedback! I appreciate your insight on this.
